FROM mcr.microsoft.com/openjdk/jdk:21-ubuntu AS builder
WORKDIR /consumer

COPY mvnw .
COPY .mvn .mvn
COPY pom.xml .
RUN --mount=type=cache,target=/root/.m2 ./mvnw dependency:resolve-plugins dependency:resolve

COPY src src
RUN --mount=type=cache,target=/root/.m2 ./mvnw package -DskipTests

FROM mcr.microsoft.com/openjdk/jdk:21-ubuntu
WORKDIR /consumer

COPY --from=builder /consumer/target/*.jar app.jar

EXPOSE 8082
ENTRYPOINT ["java", "-jar", "app.jar"]
