spring.application.name=consumer

server.port=8082

# URL base della Producer API
api.base-url=http://localhost:8081/api

# Thymeleaf
spring.thymeleaf.cache=false

# Log
logging.level.it.esercitazione.client=DEBUG
