spring.application.name=product-api

server.port=8081

spring.datasource.url=jdbc:mysql://localhost:3306/esercitazione_api
spring.datasource.username=root
spring.datasource.password=root

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Abilita l'esecuzione dei file SQL di inizializzazione (schema.sql / data.sql)
spring.sql.init.mode=always