spring.application.name=product-api

server.port=8081

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/esercitazione_api}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:root}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true


# Abilita l'esecuzione dei file SQL di inizializzazione (schema.sql / data.sql)
spring.sql.init.mode=never

#Forza l'esecuzione di data.sql DOPO la creazione/aggiornamento delle tabelle da parte di JPA/Hibernate 
spring.jpa.defer-datasource-initialization=true

# Ignora eventuali errori di inserimento/duplicati durante l'esecuzione dello script SQL
spring.sql.init.continue-on-error=true